{% set name = "pyglider" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyglider-{{ version }}.tar.gz
  sha256: 65cec779506939b9498426acc5c3538778942c307cf816a2e95bb00de9bbaa5a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bitstring
    - dask-core
    - gsw
    - netcdf4
    - pooch
    - python >=3.6
    - scipy
    - xarray

test:
  imports:
    - pyglider
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pyglider.readthedocs.io
  summary: Glider data to netCDF translation in python
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/c-proof/pyglider

extra:
  recipe-maintainers:
    - jklymak
