{% set name = "pyglider" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyglider-{{ version }}.tar.gz
  sha256: 3dda698945238ccad102abbc9d91a7c407013c825cb55d6abacdf09660a71b23

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python 3.9
    - pip
    - setuptools >=64
    - setuptools-scm >=8
  run:
    - bitstring
    - dask-core
    - gsw
    - netcdf4
    - pooch
    - python >=3.9
    - scipy
    - xarray
    - polars >=1.1
    - bottleneck
    - numpy

test:
  imports:
    - pyglider
  commands:
  requires:
    - python 3.9
    - pip

about:
  home: https://pyglider.readthedocs.io
  summary: Glider data to netCDF translation in python
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/c-proof/pyglider

extra:
  recipe-maintainers:
    - jklymak
